version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      DB_DATABASE: base
      DB_HOST:localhost
      DB_ROOT_PASSWORD: root
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local