version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senhausuario
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local